In [1]:
#Theoretical Questions

Ouestion.1 - 1. Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?



Answer - NumPy (Numerical Python) is a fundamental package for scientific computing and data analysis in Python. It provides powerful tools for working with large, multi-dimensional arrays and matrices, along with a vast collection of mathematical functions to operate on these arrays. Here’s how NumPy enhances Python's capabilities:

1. Efficient Array Handling:
Purpose: NumPy introduces the ndarray (N-dimensional array) object, which is a fast, flexible container for large datasets in Python.
Advantages: Arrays in NumPy are more memory-efficient and faster compared to Python’s built-in lists. This efficiency is critical for handling large datasets in scientific computing and data analysis.
2. Vectorized Operations:
Purpose: NumPy allows for operations on entire arrays without the need for explicit loops, known as vectorization.
Advantages: This results in concise, readable code and significantly faster execution since operations are implemented in compiled C code behind the scenes.
3. Broadcasting:
Purpose: Broadcasting is a powerful feature that allows NumPy to work with arrays of different shapes in arithmetic operations.
Advantages: It eliminates the need for explicit looping and manual resizing of arrays, simplifying code and improving performance.
4. Extensive Mathematical Functions:
Purpose: NumPy provides a wide range of mathematical operations, including basic arithmetic, linear algebra, random number generation, and Fourier transforms.
Advantages: This makes it a one-stop solution for many common numerical tasks, reducing the need to rely on multiple libraries.
5. Integration with Other Libraries:
Purpose: NumPy serves as the base for other scientific libraries such as SciPy, Pandas, Matplotlib, and TensorFlow.
Advantages: Its widespread adoption ensures seamless integration and compatibility, allowing for easy transitions between data manipulation, statistical analysis, and data visualization.
6. Memory Management:
Purpose: NumPy arrays are stored in contiguous blocks of memory, which allows for efficient computation and manipulation of large datasets.
Advantages: This reduces overhead and speeds up computations, especially in operations like slicing, reshaping, and broadcasting.
7. Interfacing with C/C++ and Fortran:
Purpose: NumPy allows for integration with low-level languages like C/C++ and Fortran, enabling the use of high-performance libraries.
Advantages: This facilitates the inclusion of legacy code or performance-critical sections of code within Python programs.




Question.2 - Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the other?


Answer - In NumPy, both np.mean() and np.average() are used to compute the average of an array's elements, but they have some differences in functionality and use cases. Here's a comparison and when to use each:

1. np.mean()
Purpose: Computes the arithmetic mean (average) of the elements along the specified axis or of the entire array if no axis is specified.
Syntax: np.mean(a, axis=None, dtype=None, out=None, keepdims=False)
-  a: Input array.
- axis: Axis along which the mean is computed. If None, computes the mean of the flattened array.
- dtype: Type to use in computing the mean.
- out: Alternate output array to place the result.
- keepdims: If True, the reduced axes are retained as dimensions with size one.

Weights: np.mean() does not support weights. All elements contribute equally to the mean.


In [6]:
#Usage Example 

import numpy as np
data = np.array([1, 2, 3, 4])
mean_value = np.mean(data)  # Output: 2.5

2. np.average()
Purpose: Computes the weighted average of the elements along the specified axis or of the entire array if no axis is specified. If no weights are provided, it functions the same as np.mean().
- Syntax: np.average(a, axis=None, weights=None, returned=False)
  a: Input array.
  axis: Axis along which the average is computed. If None, computes the average of the flattened array.
  weights: Array of weights associated with the values in a. If None, computes the arithmetic mean.
  returned: If True, returns a tuple containing the average and the sum of the weights.
  Weights: np.average() supports weights, allowing you to assign different importance to different elements.

In [9]:
#Usage Example 

import numpy as np
data = np.array([1, 2, 3, 4])
weights = np.array([1, 1, 2, 2])
weighted_avg = np.average(data, weights=weights)  # Output: 3.0


- When to Use One Over the Other:

Use np.mean() when you need the simple arithmetic mean and don’t require any weighting of the elements.

Example: Calculating the average temperature over a week without considering the duration of each recorded period.
Use np.average() when you need to compute a weighted average, where different elements in the array have different levels of importance or influence.

Example: Calculating the average grade in a course where different assignments have different weights.

Question.3 -  Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D arrays.

Answer - 1. Reversing a 1D Array
A 1D array is a single-dimensional array (like a list in Python). Reversing a 1D array involves flipping the order of its elements.

- Method 1: Using Slicing

You can reverse a 1D array by slicing it with a step of -1.


In [8]:
#Example 

import numpy as np
arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]
print(reversed_arr)  # Output: [5 4 3 2 1]


[5 4 3 2 1]


- Method 2: Using np.flip()

The np.flip() function reverses the order of elements along a specified axis. For a 1D array, it behaves the same as slicing with -1.

In [11]:
#Example

reversed_arr_1d = np.flip(arr)
print(reversed_arr_1d)


[5 4 3 2 1]


2. Reversing a 2D Array
Method 1: Reversing Along Rows (Axis 0)
Description: To reverse the rows of a 2D array (flip the array vertically), you can use slicing [::-1, :] or np.flip(arr_2d, axis=0).


In [12]:
#Example

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Using slicing
reversed_rows = arr_2d[::-1, :]
print(reversed_rows)

# Using np.flip
reversed_rows = np.flip(arr_2d, axis=0)
print(reversed_rows)


[[7 8 9]
 [4 5 6]
 [1 2 3]]
[[7 8 9]
 [4 5 6]
 [1 2 3]]


Method 2: Reversing Along Columns (Axis 1)
Description: To reverse the columns of a 2D array (flip the array horizontally), you can use slicing [:, ::-1] or np.flip(arr_2d, axis=1).

In [13]:
# Using slicing
reversed_cols = arr_2d[:, ::-1]
print(reversed_cols)

# Using np.flip
reversed_cols = np.flip(arr_2d, axis=1)
print(reversed_cols)


[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[3 2 1]
 [6 5 4]
 [9 8 7]]


Method 3: Reversing Both Axes (180° Rotation)
Description: To reverse both rows and columns (rotate the array by 180°), you can combine the two slicing methods or use np.flip() with both axe

In [14]:
# Using slicing
reversed_both = arr_2d[::-1, ::-1]
print(reversed_both)

# Using np.flip
reversed_both = np.flip(arr_2d)
print(reversed_both)


[[9 8 7]
 [6 5 4]
 [3 2 1]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]






Question.4 - How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.


Answer - Determining the Data Type of Elements in a NumPy Array.

In NumPy, you can determine the data type of elements in an array using the .dtype attribute. This attribute returns a dtype object that describes the data type of the elements in the array.

In [15]:
#Example

import numpy as np

# Create an array
arr = np.array([1, 2, 3, 4])

# Determine the data type
data_type = arr.dtype
print(data_type)


int64


Importance of Data Types in Memory Management and Performance
Data types (dtype) in NumPy are crucial for both memory management and performance. Here's why:

1. Memory Management

 Fixed Size: Each data type in NumPy has a fixed size in memory. For example, an int32 uses 4 bytes, while a float64 uses 8 bytes. Knowing the data type helps you understand how much memory an array will consume.

 Efficient Storage: Choosing the appropriate data type can optimize memory usage. For instance, using int8 (1 byte) instead of int64 (8 bytes) for a small range of integers can significantly reduce memory consumption, especially for large arrays.

 Memory Alignment: NumPy arrays are stored in contiguous blocks of memory, which optimizes cache usage and speeds up computations. Proper alignment of data types in memory further enhances performance.

2. Performance

 Vectorized Operations: NumPy performs operations in a vectorized manner, meaning operations are applied to entire arrays rather than individual elements. The speed of these operations depends on the data type, as certain operations (e.g., arithmetic) are faster on smaller or simpler data types (e.g., int32 vs. int64).
 
 Avoiding Type Casting: If operations involve arrays of different data types, NumPy may need to cast them to a common type, which can introduce overhead. -Ensuring that arrays have compatible data types can eliminate unnecessary type casting and improve performance.
 
 Specialized Instructions: Modern CPUs have specialized instructions for certain data types (e.g., SIMD instructions for floating-point arithmetic). By using the appropriate data type, NumPy can leverage these instructions, leading to faster computations.
 
Choosing the Right Data Type: 

 For Small Integers: Use int8, int16, or int32 to save memory if the range of values is small.
 
 For Floating-Point Numbers: Use float32 for single precision or float64 for double precision, depending on the required accuracy.
 
 For Boolean Values: Use bool, which only requires 1 bit per element, making it highly memory-efficient.

In [16]:
#Example: Memory and Performance Impact

import numpy as np
import time

# Large array with int32 data type
arr_int32 = np.ones(10000000, dtype=np.int32)

# Large array with int64 data type
arr_int64 = np.ones(10000000, dtype=np.int64)

# Timing a simple operation
start_time = time.time()
arr_int32_sum = np.sum(arr_int32)
print("Time for int32:", time.time() - start_time)

start_time = time.time()
arr_int64_sum = np.sum(arr_int64)
print("Time for int64:", time.time() - start_time)


Time for int32: 0.006175994873046875
Time for int64: 0.005044221878051758




Question.5 -  Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?

Answer - Defining ndarrays in NumPy
In NumPy, an ndarray (short for N-dimensional array) is a powerful data structure that represents a grid of values, all of the same type, indexed by a tuple of non-negative integers. The number of dimensions is determined by the array's shape, and each dimension is referred to as an axis.

In [17]:
#Example 

import numpy as np

# Creating a 2D ndarray
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)


[[1 2 3]
 [4 5 6]]


- Key Features of ndarrays

1.Homogeneous Data Types:

All elements in an ndarray have the same data type (dtype). This consistency allows for more efficient storage and operations.


Example - print(arr.dtype)  # Output: int64


2. Fixed Size:

Once created, the size of an ndarray is fixed, meaning you cannot change the number of elements without creating a new array. This is different from Python lists, which can dynamically grow or shrink.

3. N-dimensional:

ndarrays can have any number of dimensions (axes), making them suitable for representing complex datasets such as matrices, images, or higher-dimensional data.

Example - print(arr.shape)  # Output: (2, 3) - 2 rows and 3 columns


4. Efficient Memory Storage:

ndarrays are stored in contiguous blocks of memory, which enhances performance by improving cache efficiency and reducing memory overhead.

5. Vectorized Operations:

NumPy supports vectorized operations, meaning operations can be applied to entire arrays without the need for explicit loops. This is much faster and more concise than operating on individual elements, as you would with Python lists.

#Example arr2 = arr * 2
print(arr2)  # Output: [[2 4 6] [8 10 12]]


6. Broadcasting:

Broadcasting allows NumPy to perform operations on arrays of different shapes. This feature makes it easy to apply operations across arrays without needing to explicitly match their shapes.


#Example arr3 = arr + np.array([1, 2, 3])
print(arr3)  # Output: [[2 4 6] [5 7 9]]


7. Rich Mathematical Functions:

NumPy provides a vast array of functions that operate on ndarrays, including statistical operations, linear algebra, and random number generation.

8. Slicing and Indexing:

ndarrays support advanced slicing and indexing techniques, which allow for easy manipulation of data.



- Differences Between ndarrays and Python Lists

1. Data Type Homogeneity:

ndarray: All elements must be of the same data type.
List: Can contain elements of different data types (e.g., integers, strings, floats).

2. Memory Efficiency:

ndarray: Stored in a contiguous block of memory, leading to more efficient use of memory and faster access.
List: Elements are stored as separate objects, leading to more memory overhead.

3. Performance:

ndarray: Operations are highly optimized and performed in compiled C code, making them much faster, especially for large datasets.
List: Operations are performed in Python, which is slower, especially when operating on large datasets.

4. Fixed Size vs. Dynamic Size:

ndarray: Fixed size; you cannot change the size without creating a new array.
List: Dynamic size; you can easily add or remove elements.

5. Dimensionality:

ndarray: Naturally supports multiple dimensions (e.g., 2D arrays, 3D arrays).
List: Typically 1D, but can be nested to create multi-dimensional structures, though with more complexity and less efficiency.

6. Broadcasting:

ndarray: Supports broadcasting, allowing for operations between arrays of different shapes.
List: Does not support broadcasting; operations between lists of different sizes require manual iteration.

7. Mathematical Operations:

ndarray: Supports element-wise operations directly (e.g., addition, multiplication).
List: Requires looping or list comprehensions for element-wise operations.


 Question.6 - Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.
 
 Answer - NumPy arrays offer significant performance benefits over Python lists for large-scale numerical operations due to the following reasons:

1- Memory Efficiency: NumPy arrays store elements in contiguous memory blocks, reducing overhead and enabling faster access compared to Python lists, which store elements as separate objects.

2- Vectorized Operations: NumPy performs operations on entire arrays in compiled C code without explicit loops, leading to much faster execution compared to Python lists, which require loops in Python.

3- Homogeneous Data Types: NumPy arrays enforce a single data type for all elements, allowing for optimized and consistent processing, while Python lists can contain mixed types, leading to slower operations.

4- Broadcasting: NumPy supports broadcasting, which allows operations on arrays of different shapes without manual iteration, further enhancing performance.

Question.7 - Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and output.

Answer - In NumPy, vstack() and hstack() are used to stack arrays along different axes:

- vstack() (Vertical Stack):
- Description: Stacks arrays vertically (row-wise), adding rows.
- Usage: Arrays must have the same number of columns.

In [18]:
#Example 

import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = np.vstack((arr1, arr2))
print(result)


[[1 2 3]
 [4 5 6]]


hstack() (Horizontal Stack):

Description: Stacks arrays horizontally (column-wise), adding columns.
Usage: Arrays must have the same number of rows.

In [19]:
#Example

result = np.hstack((arr1, arr2))
print(result)


[1 2 3 4 5 6]


Question.8 - Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various array dimensions.

Answer - In NumPy, fliplr() and flipud() are used to flip arrays along different axes:

fliplr() (Flip Left-Right):

Description: fliplr() flips the array horizontally, meaning it reverses the order of columns.
Effect: It operates along the second axis (axis 1), reversing the elements in each row.
Applicable: Primarily used for 2D arrays but can also be applied to higher-dimensional arrays where it flips the last axis (columns).

In [22]:
#Example 

import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result = np.fliplr(arr)
print(result)


[[3 2 1]
 [6 5 4]
 [9 8 7]]


flipud() (Flip Up-Down):

Description: flipud() flips the array vertically, meaning it reverses the order of rows.
Effect: It operates along the first axis (axis 0), reversing the order of rows.
Applicable: Used for both 2D arrays and higher-dimensional arrays, where it flips the first axis (rows).

In [23]:
#Example

result = np.flipud(arr)
print(result)


[[7 8 9]
 [4 5 6]
 [1 2 3]]


Question.9. Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

Answer - Functionality of array_split() in NumPy

The array_split() method in NumPy is used to split an array into multiple sub-arrays. It allows you to specify the number of splits or the exact indices where the array should be split.

How array_split() Handles Uneven Splits

When the array cannot be evenly divided, array_split() handles this by distributing the elements as evenly as possible among the sub-arrays. If the total number of elements does not divide evenly by the specified number of splits, the function creates sub-arrays with different sizes, with the earlier sub-arrays being slightly larger.

In [24]:
#Example 

import numpy as np

# Create an array of 7 elements
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Split the array into 3 parts
result = np.array_split(arr, 3)

for sub_array in result:
    print(sub_array)


[1 2 3]
[4 5]
[6 7]


Question.10 -Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array operations?

Answer - Vectorization and Broadcasting in NumPy

Vectorization and broadcasting are key concepts in NumPy that enhance the efficiency of array operations by leveraging optimized, low-level computations.

Vectorization

Concept: Vectorization refers to the process of performing operations on entire arrays rather than individual elements. It uses optimized, compiled code (often in C) to apply operations across all elements simultaneously.

How It Works: Instead of using explicit Python loops, vectorized operations apply mathematical functions directly to the whole array. This reduces the overhead of Python loops and takes advantage of low-level optimizations and parallelism.

In [25]:
#Example 

import numpy as np

# Create two arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Vectorized addition
result = arr1 + arr2
print(result)


[5 7 9]


In [26]:
#Example

import numpy as np

# Create a 2D array and a 1D array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
arr_1d = np.array([10, 20, 30])

# Broadcasting: Add the 1D array to each row of the 2D array
result = arr_2d + arr_1d
print(result)


[[11 22 33]
 [14 25 36]]


- Contributions to Efficient Array Operations

1.Speed: Vectorization and broadcasting leverage highly optimized, compiled code for operations, which is much faster than equivalent Python loops.

2.Memory Efficiency: Broadcasting avoids the need to create large intermediate arrays by expanding the smaller array virtually, which saves memory and reduces overhead.

3.Code Simplicity: Both techniques simplify code by allowing concise, high-level operations instead of complex nested loops and manual array manipulation.

Practical Questions:

Question 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [29]:
import numpy as np

# Step 1: Create a 3x3 array with random integers between 1 and 100
arr = np.random.randint(1, 101, size=(3, 3))
print("Original array:")
print(arr)

# Step 2: Interchange rows and columns by transposing the array
transposed_arr = np.transpose(arr)
print("\nTransposed array:")
print(transposed_arr)


Original array:
[[ 3 98 50]
 [43 29 75]
 [81 93  1]]

Transposed array:
[[ 3 43 81]
 [98 29 93]
 [50 75  1]]


Question 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [30]:
import numpy as np

# Step 1: Generate a 1D array with 10 elements
arr = np.arange(10)  # Creates an array with elements [0, 1, 2, ..., 9]
print("Original 1D array:")
print(arr)

# Step 2: Reshape it into a 2x5 array
arr_2x5 = arr.reshape(2, 5)
print("\nReshaped to 2x5 array:")
print(arr_2x5)

# Step 3: Reshape it into a 5x2 array
arr_5x2 = arr.reshape(5, 2)
print("\nReshaped to 5x2 array:")
print(arr_5x2)


Original 1D array:
[0 1 2 3 4 5 6 7 8 9]

Reshaped to 2x5 array:
[[0 1 2 3 4]
 [5 6 7 8 9]]

Reshaped to 5x2 array:
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


Question.3 -  Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array

In [31]:
import numpy as np

# Step 1: Create a 4x4 array with random float values
arr = np.random.random((4, 4))  # Generates random floats between 0 and 1
print("Original 4x4 array:")
print(arr)

# Step 2: Add a border of zeros around the array
# Create a new array of zeros with shape (6, 6)
bordered_arr = np.zeros((6, 6))

# Place the original array in the center of the new array
bordered_arr[1:-1, 1:-1] = arr

print("\n4x4 array with a border of zeros:")
print(bordered_arr)


Original 4x4 array:
[[0.65800856 0.8036359  0.0160114  0.112998  ]
 [0.55458353 0.60943861 0.39913505 0.11783976]
 [0.96584268 0.89114275 0.60206451 0.77544791]
 [0.44523266 0.26982491 0.6648768  0.90209018]]

4x4 array with a border of zeros:
[[0.         0.         0.         0.         0.         0.        ]
 [0.         0.65800856 0.8036359  0.0160114  0.112998   0.        ]
 [0.         0.55458353 0.60943861 0.39913505 0.11783976 0.        ]
 [0.         0.96584268 0.89114275 0.60206451 0.77544791 0.        ]
 [0.         0.44523266 0.26982491 0.6648768  0.90209018 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


Question.4 -Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [32]:
import numpy as np

# Create an array of integers from 10 to 60 with a step of 5
arr = np.arange(10, 65, 5)  # Note: 65 is used as the stop value to include 60 in the array
print(arr)


[10 15 20 25 30 35 40 45 50 55 60]


Question. 5 - Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations
(uppercase, lowercase, title case, etc.) to each element.

In [33]:
import numpy as np

# Create a NumPy array of strings
arr = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase_arr = np.char.upper(arr)
lowercase_arr = np.char.lower(arr)
titlecase_arr = np.char.title(arr)
capitalize_arr = np.char.capitalize(arr)

print("Original array:")
print(arr)

print("\nUppercase array:")
print(uppercase_arr)

print("\nLowercase array:")
print(lowercase_arr)

print("\nTitlecase array:")
print(titlecase_arr)

print("\nCapitalize array:")
print(capitalize_arr)


Original array:
['python' 'numpy' 'pandas']

Uppercase array:
['PYTHON' 'NUMPY' 'PANDAS']

Lowercase array:
['python' 'numpy' 'pandas']

Titlecase array:
['Python' 'Numpy' 'Pandas']

Capitalize array:
['Python' 'Numpy' 'Pandas']


Question 6 -  Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [34]:
import numpy as np

# Step 1: Create a NumPy array of words
words_arr = np.array(['hello', 'Ayush', 'here'])

# Step 2: Insert a space between each character of every word
spaced_words_arr = np.char.join(' ', words_arr)

print("Original array:")
print(words_arr)

print("\nArray with spaces between characters:")
print(spaced_words_arr)


Original array:
['hello' 'Ayush' 'here']

Array with spaces between characters:
['h e l l o' 'A y u s h' 'h e r e']


Question 7 -  Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division. 

In [35]:
import numpy as np

# Step 1: Create two 2D NumPy arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

print("Array 1:")
print(arr1)

print("\nArray 2:")
print(arr2)

# Step 2: Perform element-wise addition
addition_result = arr1 + arr2
print("\nElement-wise addition:")
print(addition_result)

# Perform element-wise subtraction
subtraction_result = arr1 - arr2
print("\nElement-wise subtraction:")
print(subtraction_result)

# Perform element-wise multiplication
multiplication_result = arr1 * arr2
print("\nElement-wise multiplication:")
print(multiplication_result)

# Perform element-wise division
# Adding a small value to arr2 to avoid division by zero in practical cases
division_result = arr1 / (arr2 + 1e-10)
print("\nElement-wise division:")
print(division_result)


Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Element-wise addition:
[[ 8 10 12]
 [14 16 18]]

Element-wise subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]

Element-wise multiplication:
[[ 7 16 27]
 [40 55 72]]

Element-wise division:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


Question.8 -  Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [36]:
import numpy as np

# Step 1: Create a 5x5 identity matrix
identity_matrix = np.eye(5)
print("5x5 Identity Matrix:")
print(identity_matrix)

# Step 2: Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)
print("\nDiagonal elements:")
print(diagonal_elements)


5x5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Diagonal elements:
[1. 1. 1. 1. 1.]


Question 9 -  Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [37]:
import numpy as np

# Step 1: Generate a NumPy array of 100 random integers between 0 and 1000
arr = np.random.randint(0, 1000, size=100)
print("Array of random integers:")
print(arr)

# Step 2: Define a function to check for prime numbers
def is_prime(n):
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True

# Step 3: Find and display all prime numbers in the array
prime_numbers = np.array([num for num in arr if is_prime(num)])
print("\nPrime numbers in the array:")
print(prime_numbers)


Array of random integers:
[701  15  87 245 397 177 952 805 593 514 628 614 544 201  67 193 390 103
 122 132 587 174 953  97 493 554 845 707 369 771 482 897 621 170 238 194
 580 264  16 167 343 755 734 800 942 650 773 471 738 507 564 483 225 496
 379 459 863  55 644 117 955  50 424 434 275 253 892 801 693 940 838 541
 355 465 489 489 959 432 233  35 505 677 473  37  86 139 939 598 576 432
  74 826  77  72 576 950  26 365  52 685]

Prime numbers in the array:
[701 397 593  67 193 103 587 953  97 167 773 379 863 541 233 677  37 139]


Question.10 -  Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [39]:
import numpy as np

# Step 1: Create a NumPy array representing daily temperatures for a month (30 days)
# Generate random temperatures between 0 and 40 degrees Celsius
daily_temperatures = np.random.uniform(0, 40, size=30)
print("Daily temperatures for the month:")
print(daily_temperatures)

# Step 2: Reshape the array to separate weeks
# We have 30 days, so we'll reshape it into 4 weeks of 7 days and 2 extra days
weeks_count = 4
days_per_week = 7

# Create an array for full weeks and an extra part for the remaining days
temperatures_full_weeks = daily_temperatures[:weeks_count * days_per_week].reshape(weeks_count, days_per_week)
extra_days = daily_temperatures[weeks_count * days_per_week:]

print("\nTemperatures reshaped into weeks (excluding extra days):")
print(temperatures_full_weeks)

# Step 3: Calculate the weekly averages
weekly_averages = np.mean(temperatures_full_weeks, axis=1)
print("\nWeekly averages:")
print(weekly_averages)

# Display extra days if there are any
if len(extra_days) > 0:
    print("\nExtra days (not included in full weeks):")
    print(extra_days)


Daily temperatures for the month:
[18.5590848  18.85742337 11.47038374  2.25704293  7.09861244 26.67777979
 20.91615372 26.94821528 24.71286644 26.49647649 24.85455444 28.29457722
 32.46742851 17.37922465 24.25162347 10.54684503 38.01991149  8.554658
 17.43326243 35.20681257 18.34833944 12.13318289 25.95261855  4.12848207
 35.83126595 24.49538871 12.23800867 10.8444482  19.8093302  28.58874164]

Temperatures reshaped into weeks (excluding extra days):
[[18.5590848  18.85742337 11.47038374  2.25704293  7.09861244 26.67777979
  20.91615372]
 [26.94821528 24.71286644 26.49647649 24.85455444 28.29457722 32.46742851
  17.37922465]
 [24.25162347 10.54684503 38.01991149  8.554658   17.43326243 35.20681257
  18.34833944]
 [12.13318289 25.95261855  4.12848207 35.83126595 24.49538871 12.23800867
  10.8444482 ]]

Weekly averages:
[15.11949725 25.879049   21.76592178 17.94619929]

Extra days (not included in full weeks):
[19.8093302  28.58874164]
